const premierTeams = ["Arsenal", "Aston Villa", "AFC Bournemouth", "Brentford", "Brighton & Hove Albion", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Ipswich Town", "Leicester City", "Liverpool", "Manchester City", "Manchester United", "Newcastle United", "Nottingham Forest", "Southampton", "Tottenham Hotspur", "West Ham United", "Wolverhampton Wanderers"];
const bundesligaTeams = ["Bayern Munich", "Bayer Leverkusen", "VfB Stuttgart", "RB Leipzig", "Borussia Dortmund", "Eintracht Frankfurt", "SC Freiburg", "TSG Hoffenheim", "Werder Bremen", "VfL Wolfsburg", "Union Berlin", "Borussia Mönchengladbach", "FC Augsburg", "Mainz 05", "VfL Bochum", "1. FC Heidenheim", "FC St. Pauli", "Holstein Kiel"];
const laLigaTeams = ["Real Madrid", "Barcelona", "Girona", "Atlético de Madrid", "Athletic Club", "Real Sociedad", "Real Betis", "Villarreal", "Valencia", "Getafe", "Osasuna", "Mallorca", "Las Palmas", "Sevilla", "Alavés", "Rayo Vallecano", "Celta de Vigo", "Valladolid", "Leganés", "Espanyol"];
const ligue1Teams = ["Paris Saint-Germain", "AS Monaco", "Brest", "Lille", "Nice", "Lyon", "Lens", "Marseille", "Rennes", "Toulouse", "Montpellier", "Strasbourg", "Nantes", "Reims", "Le Havre", "Auxerre", "Angers", "Saint-Étienne"];
const serieAITTeams = ["Atalanta", "Bologna", "Cagliari", "Como", "Empoli", "Fiorentina", "Genoa", "Inter Milan", "Juventus", "AC Milan", "Monza", "Napoli", "Parma", "Roma", "Lazio", "Torino", "Udinese", "Venezia", "Verona", "Lecce"];
const ligabetplayTeams = ["Alianza FC", "Atlético Nacional", "Deportivo Cali", "Millonarios", "América de Cali", "Independiente Santa Fe", "Independiente Medellín", "Internacional de Bogotá", "Junior", "Llaneros", "Once Caldas", "La Equidad", "Deportes Tolima", "Envigado", "Patriotas", "Águilas Doradas", "Jaguares de Córdoba", "Deportivo Pereira", "Atlético Bucaramanga", "Fortaleza CEIF", "Unión Magdalena", "Real Cartagena", "Boyacá Chicó"];
const portuguesePrimeiraLigaTeams = ["Benfica", "Porto", "Sporting CP", "AVS", "Arouca", "Boavista", "Braga", "Casa Pia", "Estoril Praia", "Estrela da Amadora", "Farense", "Famalicão", "Gil Vicente", "Moreirense", "Nacional", "Rio Ave", "Santa Clara", "Vitória SC"];
const eredivisieTeam = ["AFC Ajax", "AZ Alkmaar", "Almere City FC", "Feyenoord", "Fortuna Sittard", "FC Groningen", "Go Ahead Eagles", "Heerenveen", "Heracles Almelo", "NAC Breda", "NEC Nijmegen", "PEC Zwolle", "PSV Eindhoven", "RKC Waalwijk", "Sparta Rotterdam", "FC Twente", "FC Utrecht", "Willem II"];
const division1ArgentinaTeams = ["Argentinos Juniors", "Atlético Tucumán", "Banfield", "Barracas Central", "Belgrano", "Boca Juniors", "Central Córdoba", "Defensa y Justicia", "Deportivo Riestra", "Estudiantes de La Plata", "Gimnasia y Esgrima La Plata", "Godoy Cruz", "Huracán", "Independiente", "Independiente Rivadavia", "Instituto", "Lanús", "Newell's Old Boys", "Platense", "Racing Club", "River Plate", "Rosario Central", "San Lorenzo", "Sarmiento", "Talleres", "Tigre", "Unión", "Vélez Sarsfield"];
const serieABrTeams = ["Athletico Paranaense", "Atlético Goianiense", "Atlético Mineiro", "Bahia", "Botafogo", "Corinthians", "Criciúma", "Cruzeiro", "Cuiabá", "Flamengo", "Fluminense", "Fortaleza", "Grêmio", "Internacional", "Juventude", "Palmeiras", "Red Bull Bragantino", "São Paulo", "Sport Recife", "Vasco da Gama"];
const superLigaTurquiaTeams = ["Adana Demirspor", "Alanyaspor", "Antalyaspor", "Beşiktaş", "Çaykur Rizespor", "Eyüpspor", "Fenerbahçe", "Galatasaray", "Gaziantep FK", "Hatayspor", "İstanbul Başakşehir", "Kasımpaşa", "Konyaspor", "Pendikspor", "Samsunspor", "Sivasspor", "Trabzonspor", "Trendyol 1. Lig Yeni Takımlar"];
const mlsTeams = ["Atlanta United", "Austin FC", "Charlotte FC", "Chicago Fire FC", "Colorado Rapids", "Columbus Crew", "D.C. United", "FC Cincinnati", "FC Dallas", "Houston Dynamo FC", "Inter Miami CF", "LA Galaxy", "Los Angeles FC", "Minnesota United FC", "CF Montréal", "Nashville SC", "New England Revolution", "New York City FC", "New York Red Bulls", "Orlando City SC", "Philadelphia Union", "Portland Timbers", "Real Salt Lake", "San Jose Earthquakes", "Seattle Sounders FC", "Sporting Kansas City", "St. Louis City SC", "Toronto FC", "Vancouver Whitecaps FC"];

var teams = {
    "hockey": ["Anaheim Ducks", "Boston Bruins", "Buffalo Sabres", "Calgary Flames", "Carolina Hurricanes", "Chicago Blackhawks", "Colorado Avalanche", "Columbus Blue Jackets", "Dallas Stars", "Detroit Red Wings", "Edmonton Oilers", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Montreal Canadiens", "Nashville Predators", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Pittsburgh Penguins", "San Jose Sharks", "Seattle Kraken", "St. Louis Blues", "Tampa Bay Lightning", "Toronto Maple Leafs", "Utah Mammoth", "Vancouver Canucks", "Vegas Golden Knights", "Washington Capitals", "Winnipeg Jets"],
    "basketball": ["Atlanta Hawks", "Boston Celtics", "Brooklyn Nets", "Charlotte Hornets", "Chicago Bulls", "Cleveland Cavaliers", "Dallas Mavericks", "Denver Nuggets", "Detroit Pistons", "Golden State Warriors", "Houston Rockets", "Indiana Pacers", "Los Angeles Clippers", "Los Angeles Lakers", "Memphis Grizzlies", "Miami Heat", "Milwaukee Bucks", "Minnesota Timberwolves", "New Orleans Pelicans", "New York Knicks", "Oklahoma City Thunder", "Orlando Magic", "Philadelphia 76ers", "Phoenix Suns", "Portland Trail Blazers", "Sacramento Kings", "San Antonio Spurs", "Toronto Raptors", "Utah Jazz", "Washington Wizards"],
    "baseball": ["Arizona Diamondbacks", "Atlanta Braves", "Baltimore Orioles", "Boston Red Sox", "Chicago Cubs", "Chicago White Sox", "Cincinnati Reds", "Cleveland Guardians", "Colorado Rockies", "Detroit Tigers", "Houston Astros", "Kansas City Royals", "Los Angeles Angels", "Los Angeles Dodgers", "Miami Marlins", "Milwaukee Brewers", "Minnesota Twins", "New York Mets", "New York Yankees", "Oakland Athletics", "Philadelphia Phillies", "Pittsburgh Pirates", "San Diego Padres", "San Francisco Giants", "Seattle Mariners", "St. Louis Cardinals", "Tampa Bay Rays", "Texas Rangers", "Toronto Blue Jays", "Washington Nationals"],
    "football": [
        ...premierTeams,
        ...bundesligaTeams,
        ...laLigaTeams,
        ...ligue1Teams,
        ...serieAITTeams,
        ...portuguesePrimeiraLigaTeams,
        ...eredivisieTeam,
        ...mlsTeams,
        ...ligabetplayTeams
        ]
}
